people = [
    { name = "Chris Angelius",        url = "https://chrisangelius.com" },
    { name = "Diana Angelius",        url = "https://www.thenode.is" },
    { name = "Gareth Chang",          url = "https://www.thenode.is" },
    { name = "Daniel Alvarez",        url = "https://www.thenode.is" },
    { name = "Felix Deimann",         url = "https://www.thenode.is" },
    { name = "Jonathan Conde",        url = "https://www.thenode.is" },
    { name = "Claudio Berinato",      url = "https://www.thenode.is" },
    { name = "Jamie Hoy",             url = "https://www.thenode.is" },
    { name = "Bamm Bamm Wolfgang",    url = "https://www.thenode.is" },
    { name = "Adam Alexander",        url = "https://www.thenode.is" },
    { name = "Gavin Doods",           url = "https://www.thenode.is" },
    { name = "James Cowen",           url = "https://www.thenode.is" },
    { name = "Keane Hughes",          url = "https://www.thenode.is" },
    { name = "Mady Henly",            url = "https://www.thenode.is" },
    { name = "Paul Stefanidis",       url = "https://www.thenode.is" },
    { name = "Leo Nguyen",            url = "https://www.thenode.is" },
]

clients = [
    { name = "node",                  url = "https://www.thenode.is" },
]

test=[ {url="https://www.thenode.is"} ]
